[project]
name = "podejmowatoinator"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Szymon", email = "01178585@pw.edu.pl"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
